---
apiVersion: v1
kind: Service
metadata:
  name: orthocal-service
  namespace: orthocal
  labels:
    app: orthocal-service
    service: api
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: orthocal-service
    service: api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orthocal-service
  namespace: orthocal
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: orthocal-service
        service: api
    spec:
      containers:
      - name: orthocal-service
        imagePullPolicy: Always
        image: brianglass/orthocal-service:latest
        resources:
          requests:
            cpu: 150m
            memory: 15Mi
          limits:
            cpu: 200m
            memory: 30Mi
        ports:
        - name: http
          containerPort: 8080
        env:
          - name: ALEXA_APP_ID
            valueFrom:
              secretKeyRef:
                name: alexa-app-id
                key: id
