apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
  namespace: orthocal
  annotations:
    kubernetes.io/ingress.global-static-ip-name: orthocal-ip
spec:
  tls:
  - secretName: orthocal-info-tls
  rules:
    - host: orthocal.info
      http:
        paths:
        - path: /api/*
          backend:
            serviceName: orthocal-service
            servicePort: 80
        - path: /echo/*
          backend:
            serviceName: orthocal-service
            servicePort: 80
        - path: /*
          backend:
            serviceName: orthocal-client
            servicePort: 80
